# Generated by Django 5.1.7 on 2025-03-28 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="country",
        ),
        migrations.RemoveField(
            model_name="location",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="location",
            name="state",
        ),
    ]
