# Generated by Django 5.1.7 on 2025-03-28 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0002_remove_location_country_remove_location_postal_code_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="email",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="gender",
        ),
    ]
