# Generated by Django 5.1.7 on 2025-04-22 07:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_remove_patient_date_of_birth_remove_patient_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(blank=True, max_length=100)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Corporate Client",
                "verbose_name_plural": "Corporate Clients",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="patient",
            name="amount_paid",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Used for grouping clients by payment amount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="medical_aid_company",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="patient",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("MEDICAL_AID", "Medical Aid")],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="refill_period_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+263783046041. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="corporate_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patients",
                to="patients.corporateclient",
            ),
        ),
    ]
