# Generated by Django 5.1.7 on 2025-05-01 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="live",
            field=models.BooleanField(
                default=False, verbose_name="Is user want to tailk live agent"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
