# Generated by Django 5.1.7 on 2025-05-01 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_customuser_live_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="platform",
            field=models.CharField(default="UNKNOWN", max_length=10),
        ),
    ]
